### ISSUE TITLE
Add credits page

### ISSUE THREAD

**Issue by KipCrossing** [Open-Source-Agriculture/soil_mate#16]
Before releasing it to the play store, we should add a credits page that links to:
- Discord
- Github

Also talks about:
- Us
- Open-source
- how to get involved
- how to request features

A picture of us and the open source agriculture logo would be nice too

**Comment by ottersp0tter** [comment]
Sounds great! I will create a branch of this once 'addingTextures' has been merged into 'main'

**Comment by KipCrossing** [comment]
This app was developed by Open Source Agriculture. 

We are siblings who are passionate about agriculture and open-source. 

To keep the development of the app free and open-source, consider supporting us by:

**Comment by KipCrossing** [comment]
Include https://pub.dev/packages/package_info

**Comment by KipCrossing** [comment]
Closed in #28
