### ISSUE TITLE
Incrementing Samples

### ISSUE THREAD

**Issue by GoldHunter89** [Open-Source-Agriculture/soil_mate#18]
Hi, would love to see a feature of incrementing sample id's for substantial sampling programs. Preferably the user enters the starting sample id (numerical but if there can be a text prefix that would be useful - capacity for 5 integers) then each subsequent sample increments by one. Cheers. 
P.s this app looks quite useful, really looking forward to testing it out.

**Comment by KipCrossing** [comment]
@ottersp0tter There are many ways to solve this problem.

We could add a `currentIncrement` property to the `Site` object *or* we could pass through the previous sample data (`incrementID`) to the `add_sample` page.

**Comment by ottersp0tter** [comment]
Sounds like a great feature! Keen to work on it

**Comment by KipCrossing** [comment]
@ottersp0tter PR #20 adds logic for the ID.

When you merge and make a new PR, all you have to do to set the ID is

in `add_sample.datt` wherever you put and update the number input

```dart
site.increment = YOUR_NEW_SAMPLE_ID_INT;
```

obv replace `YOUR_NEW_SAMPLE_ID_INT` with the variable you come up with.

**Comment by KipCrossing** [comment]
![Screenshot from 2021-01-07 17-59-28](https://user-images.githubusercontent.com/7298449/103861795-1e077b00-5112-11eb-89d6-6e1b798642f0.png)

Now you can start your sampling iteration IDs at any number
