### ISSUE TITLE
[PROBLEM] SoilMate is trademarked by Back Paddock

### ISSUE THREAD

**Issue by KipCrossing** [Open-Source-Agriculture/soil_mate#39]
See: https://soilmate.com.au/

We should consider changing the name before launch.

**Comment by KipCrossing** [comment]
https://search.ipaustralia.gov.au/trademarks/search/view/923925?q=Soil+Mate

**Comment by KipCrossing** [comment]
Soil LogR

**Comment by KipCrossing** [comment]
![Screenshot from 2021-03-11 17-11-07](https://user-images.githubusercontent.com/7298449/110743864-dc6b8b80-828c-11eb-96d0-e75b533b6426.png)

**Comment by ottersp0tter** [comment]
Soil Util, Soil Log, Soil Tool, Soil Tracker, Soil Logger, Soil Helper, Soil Smart, Smart Soil

**Comment by ottersp0tter** [comment]
Simple soil sampler, Smart soil sampler, Soil Sampler, Super soil sampler, Soil Aid

**Comment by ottersp0tter** [comment]
Soil Note, Soil Diary

**Comment by ottersp0tter** [comment]
name now Soil LogR
